# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west1
  _SERVICE: podcast-api
  _AR_REPO: cloud-run
  _MEDIA_ROOT: /tmp

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'

steps:
  # Build container image and tag as :latest
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'
      - .

  # Push the :latest image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'

  # Deploy to Cloud Run, using the :latest tag
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--remove-env-vars=SECRET_KEY,GOOGLE_CLIENT_ID,DATABASE_URL,SESSION_SECRET_KEY,GEMINI_API_KEY,ELEVENLABS_API_KEY,ASSEMBLYAI_API_KEY,SPREAKER_API_TOKEN,SPREAKER_CLIENT_ID,SPREAKER_CLIENT_SECRET,GOOGLE_CLIENT_SECRET,STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET,DB_USER,DB_PASS,DB_NAME'
      - '--update-env-vars=ADMIN_EMAIL=scott@scottgerhardt.com,MEDIA_ROOT=${_MEDIA_ROOT},OAUTH_BACKEND_BASE=https://api.getpodcastplus.com,CORS_ALLOWED_ORIGINS=https://app.getpodcastplus.com,INSTANCE_CONNECTION_NAME=podcast612:us-west1:podcast-db'
      - >-
        --update-secrets=DB_USER=DB_USER:latest,DB_PASS=DB_PASS:latest,DB_NAME=DB_NAME:latest,SECRET_KEY=SECRET_KEY:latest,SESSION_SECRET_KEY=SESSION_SECRET:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest,ASSEMBLYAI_API_KEY=ASSEMBLYAI_API_KEY:latest,SPREAKER_API_TOKEN=SPREAKER_API_TOKEN:latest,SPREAKER_CLIENT_ID=SPREAKER_CLIENT_ID:latest,SPREAKER_CLIENT_SECRET=SPREAKER_CLIENT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest