name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend (Vite)
        working-directory: frontend
        run: npm run build --if-present

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker credential helper
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.deploy
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/podcast-web:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: podcast-web
          image: gcr.io/${{ secrets.GCP_PROJECT }}/podcast-web:latest
          region: ${{ secrets.GCP_REGION }}
          allow-unauthenticated: true
          env_vars: |-
            APP_ENV=production
